builds:
- env:
    - CGO_ENABLED=0
  goos:
      - windows
      - darwin
      - linux
  goarch:
    - amd64
    - 386
  ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: x86_64 
checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: giannimassi
    name: trello-tui
  prerelease: true

  name_template: "{{.ProjectName}}-v{{.Version}}"